from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, UniqueConstraint
from sqlalchemy.sql import func
from app.db.database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    phone_number = Column(String, unique=True, index=True, nullable=False)
    full_name = Column(String, nullable=True)
    role = Column(String, default="customer")  # "customer" or "worker"
    dob = Column(String, nullable=True)
    gender = Column(String, nullable=True)
    offered_services = Column(String, nullable=True)  # JSON list or comma-separated string of subCategory IDs
    availability = Column(String, nullable=True)      # JSON string: {"days_off": [...], "dead_slots": [...]}
    referral_code = Column(String(6), unique=True, index=True, nullable=True)
    referral_points = Column(Integer, default=0, nullable=False)
    is_online = Column(Integer, default=1, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class ReferralClaim(Base):
    __tablename__ = "referral_claims"
    __table_args__ = (
        UniqueConstraint("referred_user_id", name="uq_referral_claim_referred_user"),
    )

    id = Column(Integer, primary_key=True, index=True)
    referrer_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    referred_user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    referral_code = Column(String(6), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Booking(Base):
    __tablename__ = "bookings"

    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    worker_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    service_id = Column(String(50), nullable=False)
    date = Column(String(10), nullable=False)       # YYYY-MM-DD
    time_slot = Column(String(20), nullable=False)  # e.g. "14:00-15:00"
    status = Column(String(20), default="pending")  # pending | accepted | in_progress | completed | cancelled
    address = Column(String, nullable=True)
    amount = Column(String(20), nullable=True)       # price string e.g. "299"
    start_otp = Column(String(6), nullable=True)    # generated by worker at job site to start
    end_otp = Column(String(6), nullable=True)      # generated by worker to close job
    otp = Column(String(6), nullable=True)          # legacy, kept for migration compat
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), nullable=True)


class BookingReview(Base):
    __tablename__ = "booking_reviews"
    __table_args__ = (
        UniqueConstraint("booking_id", "reviewer_id", name="uq_booking_review_reviewer"),
    )

    id = Column(Integer, primary_key=True, index=True)
    booking_id = Column(Integer, ForeignKey("bookings.id"), nullable=False, index=True)
    reviewer_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    reviewee_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    rating = Column(Integer, nullable=False)
    description = Column(String(2000), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class PlatformFeedback(Base):
    __tablename__ = "platform_feedback"

    id = Column(Integer, primary_key=True, index=True)
    booking_id = Column(Integer, ForeignKey("bookings.id"), nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    rating = Column(Integer, nullable=False)
    description = Column(String(2000), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Address(Base):
    __tablename__ = "addresses"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    tag = Column(String(50), default="Home")  # Home | Work | Other
    flat_no = Column(String(255), nullable=True)
    street = Column(String(255), nullable=True)
    area = Column(String(255), nullable=False)
    landmark = Column(String(255), nullable=True)
    city = Column(String(100), default="Nagpur")
    pincode = Column(String(20), nullable=True)
    full_address = Column(String(1000), nullable=False)
    latitude = Column(String(50), nullable=True)
    longitude = Column(String(50), nullable=True)
    is_default = Column(Integer, default=0)  # 1 for default, 0 otherwise
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), nullable=True)

